name: Build Atmosphere

on:
  push:
    branches:
      - evaron-master
    paths-ignore:
      - 'Dockerfile'
    # tags:
    #   - '[0-9]+.[0-9]+.[0-9]+'

defaults:
  run:
    shell: bash

jobs:
  build-workflow:
    uses: ./.github/workflows/build-jobs.yaml
