name: Build Atmosphere

on:
  push:
    branches:
      - evaron-master
      - feature-integration
    paths-ignore:
      - 'Dockerfile'

jobs:
  build-workflow:
    uses: ./.github/workflows/build-jobs.yaml
